# Generated by Django 3.2 on 2021-05-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(upload_to='universidades')),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nota_acceso', models.FloatField()),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidades.centro')),
            ],
            options={
                'unique_together': {('nombre', 'centro')},
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidades.centro')),
            ],
            options={
                'unique_together': {('nombre', 'centro')},
            },
        ),
        migrations.AddField(
            model_name='centro',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidades.universidad'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('curso', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('tipo_asignatura', models.CharField(max_length=50)),
                ('rama_conocimiento', models.CharField(max_length=50)),
                ('duracion', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universidades.departamento')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidades.grado')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='centro',
            unique_together={('nombre', 'localidad')},
        ),
    ]
