# Generated by Django 3.2 on 2021-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0002_alter_grado_nota_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=models.ImageField(upload_to='media/universidades'),
        ),
    ]
