# Generated by Django 3.2 on 2021-05-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0003_alter_universidad_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='creditos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
