# Generated by Django 3.2 on 2021-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidades', '0004_alter_asignatura_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='logo',
            field=models.ImageField(upload_to='universidades'),
        ),
    ]
